const knowledgebaseData = [
    {
        id: 1,
        title: "How to troubleshoot network connectivity issues?",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
        solution: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
        tags: ["networking", "troubleshooting", "internet"],
        author: "John Doe",
      },
      {
        id: 2,
        title: "How to reset your password?",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
        solution: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
        tags: ["password", "security", "authentication"],
        author: "Jane Smith",
      },
      {
          id: 3,
          title: "How to improve computer performance?",
          description: "Learn some tips and tricks to enhance your computer's performance...",
          solution: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
          tags: ["performance", "computers", "optimization"],
          author: "Alice Johnson",
          image: "https://via.placeholder.com/300",
        },
        {
          id: 4,
          title: "Common network connectivity issues",
          description: "Identify and troubleshoot common network connectivity issues...",
          solution: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
          tags: ["networking", "connectivity", "troubleshooting"],
          author: "John Doe",
          image: "https://via.placeholder.com/300",
        },
        {
          id: 5,
          title: "How to secure your Wi-Fi network?",
          description: "Learn best practices for securing your Wi-Fi network from unauthorized access...",
          solution: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
          tags: ["security", "Wi-Fi", "networking"],
          author: "Emily Brown",
          image: "https://via.placeholder.com/300",
        },
        {
          id: 6,
          title: "Troubleshooting common printer problems",
          description: "Learn how to diagnose and fix common issues with printers...",
          solution: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
          tags: ["printer", "troubleshooting", "hardware"],
          author: "Michael Johnson",
          image: "https://via.placeholder.com/300",
        },
        {
          id: 7,
          title: "Optimizing your computer's performance",
          description: "Tips and techniques to improve your computer's performance...",
          solution: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
          tags: ["performance", "optimization", "computer"],
          author: "Samantha Williams",
          image: "https://via.placeholder.com/300",
        },
        {
          id: 8,
          title: "Backing up your important data",
          description: "Best practices for backing up important files and data...",
          solution: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
          tags: ["backup", "data", "storage"],
          author: "Chris Anderson",
          image: "https://via.placeholder.com/300",
        },
        {
          id: 9,
          title: "Introduction to cybersecurity",
          description: "Basic concepts and principles of cybersecurity...",
          solution: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
          tags: ["cybersecurity", "security", "education"],
          author: "Amanda Rodriguez",
          image: "https://via.placeholder.com/300",
        },
        {
          id: 10,
          title: "How to create strong passwords?",
          description: "Guidelines for creating strong and secure passwords...",
          solution: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
          tags: ["passwords", "security", "authentication"],
          author: "Mark Thompson",
          image: "https://via.placeholder.com/300",
        },
        {
          id: 11,
          title: "Preventing malware infections",
          description: "Tips to protect your computer from malware infections...",
          solution: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
          tags: ["malware", "security", "protection"],
          author: "Jessica Lee",
          image: "https://via.placeholder.com/300",
        },
        {
          id: 12,
          title: "How to troubleshoot software issues?",
          description: "Steps to diagnose and resolve software problems...",
          solution: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
          tags: ["software", "troubleshooting", "issues"],
          author: "David Martinez",
          image: "https://via.placeholder.com/300",
        },
        {
          id: 13,
          title: "Setting up email on your mobile device",
          description: "Instructions for configuring email accounts on smartphones...",
          solution: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
          tags: ["email", "mobile", "configuration"],
          author: "Laura Adams",
          image: "https://via.placeholder.com/300",
        },
        {
          id: 14,
          title: "Protecting your privacy online",
          description: "Tips for safeguarding your privacy while browsing the internet...",
          solution: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
          tags: ["privacy", "security", "online"],
          author: "Ryan Campbell",
          image: "https://via.placeholder.com/300",
        },
        {
          id: 15,
          title: "Understanding cloud computing",
          description: "An overview of cloud computing and its benefits...",
          solution: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
          tags: ["cloud", "computing", "technology"],
          author: "Jennifer Wilson",
          image: "https://via.placeholder.com/300",
        }
  ];
  
  export default knowledgebaseData;
  